/**
 * Discord announcement draft template for regular (monthly) 9c update releases.
 *
 * Template derived from 2 real announcements the domain owner supplied (2026-09-03) — see
 * .claude/skills/announce-fanout/references/regular-update-announcement-samples.md for the
 * verbatim originals this was reverse-engineered from. This is thinner evidence than
 * arena-announce-template.ts (3 samples, byte-identical across all of them) — treat
 * anything below as "observed twice", not "confirmed fixed", until more samples arrive.
 *
 * Key findings from that investigation:
 *  - Lines 1, 4, 5 ("Hi @everyone 👋" / "You can check the full details here:" / the 🔗
 *    link line) match in structure across both samples — kept as fixed template.
 *  - Line 2 ("We will be releasing v{APV} on {Month D, YYYY} at {time} (KST).") has APV
 *    and date as variable slots. Both samples show "11:00 AM" as the time — but with only
 *    2 data points this could be coincidence (both releases happening to land in the same
 *    slot) rather than a fixed convention, so it's a caller-overridable default, not a
 *    hardcoded constant.
 *  - Line 3 (a one-line summary of what the update includes) is free text a human writes —
 *    this module never invents it, same principle as the medal-note paragraph in
 *    arena-announce-template.ts. Sample 1 has an apparent typo ("develope") in that line;
 *    since the line is always caller-supplied, this module has no copy to preserve or fix.
 *  - The link anchor is `#v{APV}` on the Gitbook release-notes page, using the same APV as
 *    line 2 — one input feeds both slots, so a version typo can't make the two disagree
 *    (unlike a template with two independently-typed occurrences of the same value).
 *
 * Relationship to announce-fanout.ts's buildAnnouncementDraft: that function repackages
 * TextNotice{,_KR,_JP}.json content (in-game notice board) into Discord sections — built
 * before any real Discord sample existed, as the best available proxy. The 2 real samples
 * behind this module show the actual posted format is much shorter and doesn't include
 * the in-game notice text at all. The two functions are kept as separate tools, not merged
 * or one replacing the other — see the reference doc above for why.
 */

const DEFAULT_RELEASE_TIME_KST = "11:00 AM";

export interface CalendarDate {
  readonly year: number;
  readonly month: number; // 1-12
  readonly day: number;
}

export interface RegularUpdateAnnouncement {
  readonly apv: number;
  readonly releaseDate: CalendarDate;
  /** Defaults to "11:00 AM" — see module doc: observed in only 2 samples, not confirmed
   *  as a fixed convention. Override when the actual planned time differs. */
  readonly releaseTimeKst?: string;
  /** Free text, always human-written. Never generated by this module. */
  readonly summary: string;
}

export interface AnnounceCheck {
  readonly id: string;
  readonly name: string;
  readonly ok: boolean;
  readonly level: "OK" | "WARN" | "FATAL";
  readonly detail: string;
}

function formatCalendarDate(d: CalendarDate): string {
  const date = new Date(Date.UTC(d.year, d.month - 1, d.day));
  return new Intl.DateTimeFormat("en-US", { year: "numeric", month: "long", day: "numeric", timeZone: "UTC" }).format(date);
}

/** Today's calendar date in KST — the timezone the announcement's own time slot is stated
 *  in, so "is the release date in the past" is judged against the same clock. */
export function todayKst(now: Date = new Date()): CalendarDate {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Seoul",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).formatToParts(now);
  const map = Object.fromEntries(parts.map((p) => [p.type, p.value]));
  return { year: Number(map.year), month: Number(map.month), day: Number(map.day) };
}

/**
 * 달력에 실제로 있는 날짜인지 (2026-09-04 추가).
 *
 * `Date.UTC`는 범위를 벗어난 값을 **조용히 넘긴다** — 실측: 2026-02-30 → "March 2, 2026",
 * 2026-09-31 → "October 1, 2026", 2026-13-01 → "January 1, 2027"(해까지 바뀐다). 이 도구는
 * @everyone 공지 초안에 출시일을 박으므로, 담당자가 친 날짜와 다른 날짜가 조용히 나가는 건
 * 그 자체로 사고다. 그래서 FATAL로 막는다.
 */
export function isRealCalendarDate(d: CalendarDate): boolean {
  if (!Number.isInteger(d.year) || !Number.isInteger(d.month) || !Number.isInteger(d.day)) return false;
  if (d.month < 1 || d.month > 12 || d.day < 1) return false;
  const daysInMonth = new Date(Date.UTC(d.year, d.month, 0)).getUTCDate();
  return d.day <= daysInMonth;
}

function compareDates(a: CalendarDate, b: CalendarDate): number {
  return a.year - b.year || a.month - b.month || a.day - b.day;
}

export function checkAnnouncement(input: RegularUpdateAnnouncement, today: CalendarDate = todayKst()): AnnounceCheck[] {
  const checks: AnnounceCheck[] = [];

  const summary = input.summary.trim();
  checks.push({
    id: "summary-non-empty",
    name: "업데이트 요약 문구 존재",
    ok: summary.length > 0,
    level: summary.length > 0 ? "OK" : "FATAL",
    detail: summary.length > 0 ? summary : "요약 문구가 비어 있습니다 — 이 줄은 사람이 직접 써야 합니다(자동 생성하지 않음).",
  });

  const realDate = isRealCalendarDate(input.releaseDate);
  const { year: y, month: mo, day: dd } = input.releaseDate;
  checks.push({
    id: "release-date-is-real",
    name: "출시일이 실재하는 날짜",
    ok: realDate,
    level: realDate ? "OK" : "FATAL",
    detail: realDate
      ? `${formatCalendarDate(input.releaseDate)} — 달력에 있는 날짜입니다.`
      : `${y}-${String(mo).padStart(2, "0")}-${String(dd).padStart(2, "0")}은 달력에 없는 날짜입니다 — 그대로 두면 다른 날짜로 굴러가 공지에 나갑니다(실측: 2026-02-30 → March 2, 2026 / 2026-13-01 → January 1, 2027).`,
  });

  const apvOk = Number.isInteger(input.apv) && input.apv > 0;
  checks.push({
    id: "apv-positive",
    name: "APV가 양의 정수",
    ok: apvOk,
    level: apvOk ? "OK" : "FATAL",
    detail: apvOk ? `v${input.apv}` : `APV가 양의 정수가 아닙니다(입력: ${input.apv}) — 공지에 "v${input.apv}"로 그대로 찍힙니다.`,
  });

  // 날짜가 실재하지 않으면 과거 여부는 판정할 수 없다. 예전엔 그 경우가 isPast=false로 떨어져
  // OK가 됐는데, 그 OK 문구가 formatCalendarDate로 굴러간 날짜(2026-02-30 → "March 2, 2026")를
  // "오늘 이후로 정상 범위"라고 단언했다 — 사람이 친 적 없는 날짜를, 그것도 실제로는 과거인
  // 날짜를 확인해준 것처럼 보이는 조용한 OK다. "미실행 != 확인했는데 정상" 원칙대로 WARN으로
  // 내리고, 굴러간 날짜는 아예 보여주지 않는다(위 release-date-is-real FATAL이 원본을 보여준다).
  const isPast = realDate && compareDates(input.releaseDate, today) < 0;
  const rawDate = `${y}-${String(mo).padStart(2, "0")}-${String(dd).padStart(2, "0")}`;
  checks.push({
    id: "release-date-not-past",
    name: "출시일이 과거가 아님",
    ok: realDate && !isPast,
    level: realDate && !isPast ? "OK" : "WARN",
    detail: !realDate
      ? `${rawDate}은 달력에 없는 날짜라 과거 여부를 판정하지 않았습니다 — 위 FATAL을 고친 뒤 다시 실행하세요(확인해서 정상이라는 뜻이 아닙니다).`
      : isPast
        ? `출시일(${formatCalendarDate(input.releaseDate)})이 오늘(KST 기준 ${formatCalendarDate(today)})보다 과거입니다 — 날짜 오타나 이전 초안 재사용이 아닌지 확인하세요.`
        : `${formatCalendarDate(input.releaseDate)} — 오늘(KST 기준 ${formatCalendarDate(today)}) 이후로 정상 범위.`,
  });

  const time = input.releaseTimeKst ?? DEFAULT_RELEASE_TIME_KST;
  if (time !== DEFAULT_RELEASE_TIME_KST) {
    checks.push({
      id: "release-time-deviates-from-observed",
      name: "출시 시각이 과거 관측치와 다름",
      ok: true,
      level: "WARN",
      detail: `과거 샘플 2건은 전부 "${DEFAULT_RELEASE_TIME_KST} (KST)"였는데 이번 값은 "${time}"입니다 — 관측 2건뿐이라 이게 규칙 위반인지 의도적 변경인지는 판단할 수 없습니다. 의도한 값인지만 확인하세요.`,
    });
  }

  return checks;
}

export interface AnnouncementDraft {
  readonly body: string;
  readonly checks: AnnounceCheck[];
}

export function buildAnnouncementDraft(input: RegularUpdateAnnouncement, today: CalendarDate = todayKst()): AnnouncementDraft {
  const checks = checkAnnouncement(input, today);
  const time = input.releaseTimeKst ?? DEFAULT_RELEASE_TIME_KST;

  const body = [
    "Hi @everyone 👋",
    `We will be releasing v${input.apv} on ${formatCalendarDate(input.releaseDate)} at ${time} (KST).`,
    input.summary.trim(),
    "You can check the full details here:",
    `🔗 https://docs.nine-chronicles.com/introduction/intro/roadmap-and-completed/release-notes#v${input.apv}`,
  ].join("\n");

  return { body, checks };
}

export function overallLevel(checks: readonly AnnounceCheck[]): "OK" | "WARN" | "FATAL" {
  if (checks.some((c) => c.level === "FATAL")) return "FATAL";
  if (checks.some((c) => c.level === "WARN")) return "WARN";
  return "OK";
}
